apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-demo
  template:
    metadata:
      labels:
        app: kubectl-demo
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: kubectl-demo
        image: docker/tilt:v0.34.0
        command: ["/scripts/kubectl-demo.sh"]
        volumeMounts:
        - name: demo-script
          mountPath: /scripts
      volumes:
      - name: demo-script
        configMap:
          name: demo-script
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: demo
        image: ghcr.io/mkmik/surprising-kubeconfig:latest
        command: ["/scripts/demo.sh"]
        volumeMounts:
        - name: demo-script
          mountPath: /scripts
      volumes:
      - name: demo-script
        configMap:
          name: demo-script
          defaultMode: 0755
