apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml

configMapGenerator:
- name: demo-script
  namespace: demo
  files:
  - demo.sh
  - kubectl-demo.sh
  - kubeconfig
